# the changes will happen to the main branch hence 'master'
trigger:
- master

#hosted build agent, you can choose wich OS should be running your build
pool:
  vmImage: 'vm'

steps:
# the first step is the installation of Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

# with this you run the script in this example it's npm install
- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
#this task bundles your code in a zip file to the specified folder
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
